                            ___             
                        __ /\_ \            
 _____   __  __  _____ /\_\\//\ \     ___   
/\ '__`\/\ \/\ \/\ '__`\/\ \ \ \ \   / __`\ 
\ \ \L\ \ \ \_\ \ \ \L\ \ \ \ \_\ \_/\ \L\ \
 \ \ ,__/\/`____ \ \ ,__/\ \_\/\____\ \____/
  \ \ \/  `/___/> \ \ \/  \/_/\/____/\/___/ 
   \ \_\     /\___/\ \_\                    
    \/_/     \/__/  \/_/                    


FAIL
2020AUG16
* problem resizing one odd size, jpg image
* error reported, debug on

    pmbp:2020AUG16 pr$ $HOME/work/code/py/pypilo/process.py -i d1/ -o u1/
    > source: <d1/> is dir True
    > tools.get_filenames.filepath <d1/>
    > tools.get_filenames.fpn <d1/*.*>
    > tools.get_filenames <['d1/wilkesneilyoungfireplace.jpg']>
    > files ['d1/wilkesneilyoungfireplace.jpg']
    > process
    > processing
    > sfpn <d1/wilkesneilyoungfireplace.jpg>
    > filepath2title
    > filepath <d1>
    > filename <wilkesneilyoungfireplace.jpg>
    > source filepath <d1>
    > source filename <wilkesneilyoungfireplace.jpg>
    > file exist: <d1/wilkesneilyoungfireplace.jpg> is True
    > fn jpg <wilkesneilyoungfireplace.jpg> is [25]
    >> fn <2020AUG161414520.244.jpg>
    > sr_fp d1
    > dest_fp u1/
    > s_fn wilkesneilyoungfireplace.jpg
    > d_fn 2020AUG161414520.244.jpg
    > pil_resize
    > source fp <d1>
    > dest   fp <u1/>
    > 1. sfpn <d1/wilkesneilyoungfireplace.jpg>
    > 2. src <d1/wilkesneilyoungfireplace.jpg>
    > 3. dest <u1/2020AUG161414520.244.jpg>
    > 4. open <d1/wilkesneilyoungfireplace.jpg>
    > height <207>
    > width  <300>
    > ratio <1.4492753623188406>
    > setting image w<1330> h<917> r<1.4492753623188406>
    > w (1330) h (917)
    > 5. resize image
    > 6. save image by TYPE
    > dfpn <u1/2020AUG161414520.244.jpg>
    > ext <jpg>
    Traceback (most recent call last):
      File "/Users/pr/work/code/py/pypilo/process.py", line 262, in <module>
        main()
      File "/Users/pr/work/code/py/pypilo/process.py", line 250, in main
        if process(afiles, dest_fp):
      File "/Users/pr/work/code/py/pypilo/process.py", line 109, in process
        process_image(sfp, dfp, sfn, dfn, IMG_JPG)
      File "/Users/pr/work/code/py/pypilo/process.py", line 153, in process_image
        if not pil_resize(sfp, dfp, sfn, dfn, ext):
      File "/Users/pr/work/code/py/pypilo/pil_tools.py", line 189, in pil_resize
        ir.save(dfpn, ext)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Pillow-6.2.0.dev0-py3.8-macosx-10.14-x86_64.egg/PIL/Image.py", line 2073, in save
      KeyError: 'JPG'


FAIL
2019NOV03
* probelms with .mp4 uploading and processing

* error reported
- debug off

  pypilo pr$ ./process.py -i $HOME/work/flickr/2019/2019NOV/2019NOV03/d1/ -o $HOME/work/flickr/2019/2019NOV/2019NOV03/u1
  ...+Traceback (most recent call last):
    File "./process.py", line 212, in <module>
      main()
    File "./process.py", line 200, in main
      if not process(afiles, dest_fp):
    File "./process.py", line 77, in process
      process_video(s_fp, dest_fp, s_fn, d_fn)
  TypeError: process_video() takes 1 positional argument but 4 were given

* change 

   - process_video(s_fp, dest_fp, s_fn, d_fn)
   + process_video(s_fp)


FAIL
2019OCT29
* problems with non-standard sized images

* error reported 
- debug on 
- post fix

  $ ./process.py -i $HOME/work/flickr/2019/2019OCT/2019OCT29/d -o /Users/pr/work/flickr/2019/2019OCT/2019OCT29/u
  $ Warning: unable to resize image

* a couple of problems looked at:
- resize of non-standard image (fixed)
- print errors instead of using debug
  

2019OCT26
* problem with input files of differing types to .jpg

* error reported
- without debug
./process.py -i $HOME/work/flickr/2019/2019OCT/2019OCT26/* -o $HOME/work/flickr/2019/2019OCT/2019OCT26/u
.Warning: file not processed
	<2019OCT261432261.png>

- debug
./process.py -i $HOME/work/flickr/2019/2019OCT/2019OCT26/* -o $HOME/work/flickr/2019/2019OCT/2019OCT26/u
> path: </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d>
> tools.get_filenames.filepath </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d>
> tools.get_filenames.fpn </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/*.*>
> tools.get_filenames <['/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432261.png', '/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432260.jpg']>
> files ['/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432261.png', '/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432260.jpg']
> destination: (2) <['/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432261.png', '/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432260.jpg']>
> processing
> source </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d> <2019OCT261432260.jpg>
.
> source fp </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d>
> dest   fp </Users/pr/work/flickr/2019/2019OCT/2019OCT26/u>
> src </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432260.jpg>
> dest </Users/pr/work/flickr/2019/2019OCT/2019OCT26/u/2019OCT261626480.267.jpg>
> height <384>
> width  <685>
> ratio <1.7838541666666667>
> setting image w<1330> h<745> r<1.7838541666666667>
> 1330:745
> <2019OCT261626480.267.jpg>
	format(JPEG) size((1330, 745)) mode:(RGB)
> source </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d> <2019OCT261432261.png>
Warning: file not processed
	<2019OCT261432261.png>

FAIL
2019SEP21
* problem with sys module in pil_tools.py
- known: we identifing an mp4 file

* error reported:

    OSError: cannot identify image file '/Users/pr/work/flickr/2019/2019SEP/2019SEP21/d/IMG_6353.m4v'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "./process.py", line 130, in <module>
        main()
      File "./process.py", line 114, in main
        process(s_fp, dest_fp, s_fn, d_fn)
      File "./process.py", line 51, in process
        pil_resize(src_fp, dest_fp, s_fn, d_fn)
      File "/Users/pr/work/code/py/pypilo/pil_tools.py", line 142, in pil_resize
      sys.exit(1)
      NameError: name 'sys' is not defined

* what I found: 
- trying to process a list of files, the code ran into a mp4 file and threw an error

* steps to reproduce:

   ./process.py -i $HOME/work/code/flickr/2019/2019SEP/2019SEP21/d -o $HOME/work/code/flickr/2019/2019SEP/2019SEP21/u

* what I want:
- to be able to process files with various different file types and handle the result.
 
2019SEP14
1 * problems with resizing
  - specified image constraints (by H)
  - resized the image by percentage (h/3.5 and w/3.5
  - but this wrong so work this out so the ratio is maintained

1 * problems with selecting filenames in uppercase
  - can't re ad filenames if uppercase
